import Head from 'next/head'
import HeaderComponent from '../components/HeaderComponent'
import SearchComponent from '../components/SearchComponent'
import FoooterComponent from '../components/FoooterComponent'

export default function Home() {
  console.log('google')
  return (
    <div className='flex flex-col h-screen'>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/iconfinder_new-google-favicon_682665.png" />
      </Head>
      <HeaderComponent home />
      <main className='flex-grow'>
        <SearchComponent />
      </main>
      <FoooterComponent />
    </div>
  )
}
