import React from 'react'
import Head from 'next/head'
import HeaderComponent from '../components/HeaderComponent';
import SearchResultsComponent from '../components/SearchResultsComponent';
import PaginationButton from '../components/PaginationButton';
import Reponse from '../dummyData'

const Search = ({results, term}) => {
    console.log(results.items)

    return (
        <div className='flex flex-col h-screen'>
            <Head>
                <title>{term} - Google Search</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/iconfinder_new-google-favicon_682665.png" />
            </Head>
            <HeaderComponent />
            <SearchResultsComponent results={results} />
            <PaginationButton length={results.items && results.items.length} />
        </div>
    )
}

export default Search

export async function getServerSideProps(context){
    const dummyData = false;
    const startIndex = context.query.start || 0

    const data = dummyData ? Reponse : await fetch(`https://www.googleapis.com/customsearch/v1?key=${process.env.API_KEY}&cx=${process.env.CONTEXT_kEY}&q=${context.query.term}&start=${startIndex}`).then(res => res.json());

    return {
        props: {
            results: data,
            term: context.query.term
        }
    }
}
